import { c as create_ssr_component, e as escape, a as add_attribute } from "../../../chunks/ssr.js";
import { S as SITE_URL, a as SITE_TITLE, b as SITE_DESCRIPTION, D as DEFAULT_OG_IMAGE, M as MY_TWITTER_HANDLE } from "../../../chunks/siteConfig.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${$$result.head += `<!-- HEAD_svelte-1w1ybsz_START -->${$$result.title = `<title>Writings - ${escape(SITE_TITLE)}</title>`, ""}<link rel="canonical"${add_attribute("href", SITE_URL, 0)}><link rel="alternate" type="application/rss+xml"${add_attribute("href", SITE_URL + "/api/rss.xml", 0)}><meta property="og:url"${add_attribute("content", SITE_URL, 0)}><meta property="og:type" content="article"><meta property="og:title"${add_attribute("content", SITE_TITLE, 0)}><meta name="Description"${add_attribute("content", SITE_DESCRIPTION, 0)}><meta property="og:description"${add_attribute("content", SITE_DESCRIPTION, 0)}><meta property="og:image"${add_attribute("content", DEFAULT_OG_IMAGE, 0)}><meta name="twitter:card" content="summary"><meta name="twitter:creator"${add_attribute("content", "@" + MY_TWITTER_HANDLE, 0)}><meta name="twitter:titl\`e"${add_attribute("content", SITE_TITLE, 0)}><meta name="twitter:description"${add_attribute("content", SITE_DESCRIPTION, 0)}><meta name="twitter:image"${add_attribute("content", DEFAULT_OG_IMAGE, 0)}><!-- HEAD_svelte-1w1ybsz_END -->`, ""} <h1 class="text-4xl font-catamaran text-semibold mt-16 text-gray-800 dark:text-gray-200 mb-10" data-svelte-h="svelte-kbi515">Writings</h1> <section class="w-full sm:w-2/5 font-catamaran text-gray-800 dark:text-gray-300" data-svelte-h="svelte-1wcn18s"><p class="text-justify text-lg">I try to write my learnings, thoughts and experiences regularly.</p> <p class="mt-4 text-justify text-lg">Starting soon, I will share them on Twitter in a condensed manner as well as
		write travel, tech, and other informative blogs here.</p> <p class="mt-4 text-justify text-lg">Please check back in some time.</p></section>`;
});
export {
  Page as default
};
